### ISSUE TITLE
Fail gracefully when presented with a result that isn't valid JSON

### ISSUE THREAD

**Issue by mcookhome** [HubSpot/algebra-public#8]
Currently, when handed a result that isn't valid JSON, the ResultDeserializer will throw a `NullPointerException`. Can that please be changed to fail more gracefully? 

```java

java.lang.NullPointerException: null
	at com.hubspot.algebra.ResultDeserializer.deserialize(ResultDeserializer.java:33)
	at com.hubspot.algebra.ResultDeserializer.deserialize(ResultDeserializer.java:17)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2874)
	at com.hubspot.connect.http.AbstractHttpResponse.getAs(AbstractHttpResponse.java:75)
	at com.hubspot.engagements.emails.client.EngagementsEmailClient.createEmailEngagement(EngagementsEmailClient.java:48)
	at com.hubspot.engagements.emails.data.FacsimileEmailSendingManager.createEngagement(FacsimileEmailSendingManager.java:277)
	at com.hubspot.engagements.emails.data.FacsimileEmailSendingManager.scheduleEmail(FacsimileEmailSendingManager.java:223)
	at com.hubspot.engagements.emails.data.FacsimileEmailSendingManager.scheduleEmail(FacsimileEmailSendingManager.java:167)
	at com.hubspot.engagements.emails.service.resources.SendEmailResource.scheduleEmail(SendEmailResource.java:89)
	at com.yammer.metrics.guice.TimedInterceptor.lambda$forMethodSync$0(TimedInterceptor.java:42)
	at sun.reflect.GeneratedMethodAccessor392.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
```

**Comment by mjball** [comment]
Could you include an example of the JSON this failed on?

**Comment by mcookhome** [comment]
```{"status":"error","message":"one or more associations are not valid","correlationId":"c4c36507-138c-4dfb-af4d-ef45ab3d9fb1","validationResults":[{"row":{"portalId":4397994,"definition":{"name":"CONTACT_TO_ENGAGEMENT","id":9,"inverseId":10,"category":"HUBSPOT_DEFINED","cardinality":"ONE_TO_MANY","fromObjectType":"CONTACT","toObjectType":"ENGAGEMENT","maxToObjectIds":10000},"fromObjectId":6501,"fromObjectType":"CONTACT"},"result":"SUCCESS"},{"row":{"portalId":4397994,"definition":{"name":"COMPANY_TO_ENGAGEMENT","id":7,"inverseId":8,"category":"HUBSPOT_DEFINED","cardinality":"ONE_TO_MANY","fromObjectType":"COMPANY","toObjectType":"ENGAGEMENT","maxToObjectIds":10000},"fromObjectId":743554499,"fromObjectType":"COMPANY"},"result":"SUCCESS"},{"row":{"portalId":4397994,"definition":{"name":"DEAL_TO_ENGAGEMENT","id":11,"inverseId":12,"category":"HUBSPOT_DEFINED","cardinality":"ONE_TO_MANY","fromObjectType":"DEAL","toObjectType":"ENGAGEMENT","maxToObjectIds":10000},"fromObjectId":272228350,"fromObjectType":"DEAL"},"result":"INVALID_FROM_OBJECT"},{"row":{"portalId":4397994,"definition":{"name":"DEAL_TO_ENGAGEMENT","id":11,"inverseId":12,"category":"HUBSPOT_DEFINED","cardinality":"ONE_TO_MANY","fromObjectType":"DEAL","toObjectType":"ENGAGEMENT","maxToObjectIds":10000},"fromObjectId":272068392,"fromObjectType":"DEAL"},"result":"SUCCESS"}],"errorMessages":["DEAL=272228350 is not a valid object"],"requestId":"55f85be1-4925-49b7-ab84-a57e1dc657f6"}```

**Comment by mjball** [comment]
Here's a more-nicely-formatted version of that JSON: https://gist.github.com/mjball/4381d5842eca21c0f62e83811d8e908c

**Comment by mcookhome** [comment]
Thanks @mjball
